import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EAF2FF",
  },
  header: {
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 3,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#083070",
    marginLeft: 8,
  },
  headerCount: {
    fontSize: 14,
    color: "#083070",
    position: "relative",
    top: 3,
    fontWeight: "500",
  },
  componentCard: {
    marginVertical: 20,
    marginHorizontal: 16,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    position: "relative", 
  },
  unreadCard: {
    backgroundColor: "#B3CCF3",
  },
  fixedBadge: {
    position: "absolute",
    top: 10,
    right: 12,
    backgroundColor: "#F1215A",
    borderRadius: 20,
    paddingHorizontal: 7,
    paddingVertical: 4,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  badgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "400",
    fontStyle: "italic",
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#EAF2FF",
    justifyContent: "center",
    alignItems: "center",
  },
  textWrapper: {
    flex: 1,
    marginLeft: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  text: {
    maxWidth: "92%",
  },
  title: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
  },
  description: {
    fontSize: 12,
    color: "#534B4B",
    marginTop: 4,
    fontStyle: "italic",
  },
  time: {
    fontSize: 12,
    color: "#534B4B",
    marginTop: 8,
  },
});
